# -*- coding: utf-8 -*-
"""readme.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uWxtk3evlvYUy6JBldY8g-W_Lx1iUyHg

# Flight Performance

## by Ahad Alotaibi

## Project Details
>This project was done as a part of Udacity's Data Analyst Nanodegree program. The objective of this project was to use Python visualization libraries to explore a dataset systematically. The analysis begins with exploring single variables followed by bivariate and multivariate analysis.

>This analysis is followed by a short presentation to convey and highlight important findings using explanatory data analysis. A slide deck was prepared that followed the major path of exploration and a story was constructed for the readers to understand what was discovered.

## Dataset

>This dataset was selected from the list provided by Udacity. It is the Flights dataset that reports flight performance metric in the US. Data explored and analyzed is for 2008 year. The data is available from Bureau of Transportation Statistics official website.

>Link to dataset: http://stat-computing.org/dataexpo/2009/the-data.html

>Link to Bureau of Transportation Statistics: https://www.transtats.bts.gov/OT_Delay/OT_DelayCause1.asp

## Summary of Findings

>After analyzing this data, we found that the highest cause of delays came from the carrier or weather related problems. American Airlines was the worst performing carrier with highest delays and cancellations in 2008. This has been shown in the presentation with the help of graphs and charts.

## Key Insights for Presentation

>  

*   Carrier and weather-related cancellations were most common.
*   American Airlines performed the worst in terms of both delays and cancellations.
*   Weather related delays were more significant as we saw in the comparison of delay reasons.
*   There is Linear relationship between departure and arrival delays
*   The top 50 busiest destinations, the number of flights does influence average arrival delay and .
*   The top 50 busiest Origin, the number of flights does influence average Departure delay
"""